language: python
os:
- linux
compiler:
- clang
- gcc
python:
- 2.7
- 3.6
- 3.7
before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python cmake hdf5 openmpi;
  fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install cmake libhdf5-serial-dev
  python-dev openmpi-bin libopenmpi-dev; fi
install:
- pip install scikit-build
- pip install mpi4py
- pip install -e .
- echo $PYTHONPATH
- echo $LD_LIBRARY_PATH
branches:
  only:
  - develop
script:
- pytest -m "not distributed_test" tests/
- mpiexec -n 2 pytest -m distributed_test tests/

jobs:
  allow_failures:
    - python: 2.7

deploy:
  provider: pypi
  user: __token__
  password:
    secure: L9uC3gvtP8diHtW6ufiuO5+zWzzOIcKcBu28NI5h2ERxBDBt0tSpFNYm568nV0I0+zNW69k+YHtco1fIRWVli56//wbwVX5vlhhyfa29eSfNrPTliVEA5JPMt/GhEjuzfylBt4HYoFAXwy8G6KVRyqptq2XUHD5DE08wuRyLbXMqOp254PRhfN+P3Yragi4CyV8H3lvG2eec/U93SOmJcSmHvYCe7AqcGl7uIuVLes+GI2APJkMv8katwHTawcJ9cssxMWLD9QUKhAnwu/JjKYo53IPrgy0xszNLE4ahLAsHKCyJAECvdA7tRNKHuXy/7vA5fA8aTrG3b1ylpw87LzP2zOfBnFa5QUhhyF011Aixgi7ivIb6uZ8X8dJ02c4NZwlRrIdzb4olCyo8dSZcLudnw+PgtQt01dLFcIVROULUU5mgcm3EMdsbUKFIHgn65GF6X3nau8PKDk8tEGTzKsbOb+ipi00WfP7rardCAoif9GpO3Nl1jCZEkFC7bmWPjSkSqZEEnF7u4efmk20EX0rQW2+YLVqGL23CnT/nVgl2RReiCzy/PoF3AIi4emQzWSJSFxnF69TBOrzJ3mjLwBIFr5nvr/c9PpDp5uNFKwxRs90hXma9M5GppngkwZF8t6Ge/lNmr/lFE0A+OWrynAu1VGaFVBeLAyyMU/tupxA=
  on:
    tags: true