language: python
python:
  - 2.7
  - 3.6

before_install:

  # Here we just install Miniconda, which you shouldn't have to change.
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda

install:

  # We just set up a conda environment with the right Python version. This
  # should not need changing.

  - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
  - source activate test

  # Below, include the dependencies you want to install with conda, optionally
  # specifying versions used in the matrix above. If you split this into
  # multiple conda install commands, you should always include numpy=$NUMPY as
  # the first package to install (for every conda install command) otherwise
  # numpy may be automatically upgraded.

  - conda install --yes swig numpy cmake hdf5 pytest scikit-build pip 

  # You can also install some dependencies with pip if not available in conda

  # - pip install ...

script:

  - py.test  # will run all tests in the package

install:
  - python setup.py install

branches:
  only:
    - develop
# services:
# - docker
# install:
# - docker build -t larcv2_image -f .Dockerfile .
# script:
# - docker run --name test_build larcv2_image python -c "import larcv"
# notifications:
# Emails are sent to the committer's git-configured email address by default,
# but only if they have access to the repository.  To enable Travis on your
# public fork of Caffe, just go to travis-ci.org and flip the switch on for
# your Caffe fork.  To configure your git email address, use:
#     git config --global user.email me@example.com
  # email:
    # on_success: always

script: pytest tests/