# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_larcv')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_larcv')
    _larcv = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_larcv', [dirname(__file__)])
        except ImportError:
            import _larcv
            return _larcv
        try:
            _mod = imp.load_module('_larcv', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _larcv = swig_import_helper()
    del swig_import_helper
else:
    import _larcv
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

kDEBUG = _larcv.kDEBUG
kINFO = _larcv.kINFO
kNORMAL = _larcv.kNORMAL
kWARNING = _larcv.kWARNING
kERROR = _larcv.kERROR
kCRITICAL = _larcv.kCRITICAL
kMSG_TYPE_MAX = _larcv.kMSG_TYPE_MAX
class logger(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, logger, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, logger, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _larcv.new_logger(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _larcv.delete_logger
    __del__ = lambda self: None

    def name(self):
        return _larcv.logger_name(self)

    def set(self, level):
        return _larcv.logger_set(self, level)

    def level(self):
        return _larcv.logger_level(self)

    def __lt__(self, rhs):
        return _larcv.logger___lt__(self, rhs)
    if _newclass:
        get = staticmethod(_larcv.logger_get)
    else:
        get = _larcv.logger_get
    if _newclass:
        get_shared = staticmethod(_larcv.logger_get_shared)
    else:
        get_shared = _larcv.logger_get_shared
    if _newclass:
        default_level = staticmethod(_larcv.logger_default_level)
    else:
        default_level = _larcv.logger_default_level
    if _newclass:
        force_level = staticmethod(_larcv.logger_force_level)
    else:
        force_level = _larcv.logger_force_level

    def debug(self):
        return _larcv.logger_debug(self)

    def info(self):
        return _larcv.logger_info(self)

    def normal(self):
        return _larcv.logger_normal(self)

    def warning(self):
        return _larcv.logger_warning(self)

    def error(self):
        return _larcv.logger_error(self)

    def send(self, *args):
        return _larcv.logger_send(self, *args)
logger_swigregister = _larcv.logger_swigregister
logger_swigregister(logger)
cvar = _larcv.cvar
kINVALID_LONGLONG = cvar.kINVALID_LONGLONG
kINVALID_ULONGLONG = cvar.kINVALID_ULONGLONG
kINVALID_SIZE = cvar.kINVALID_SIZE
kINVALID_INT = cvar.kINVALID_INT
kINVALID_UINT = cvar.kINVALID_UINT
kINVALID_SHORT = cvar.kINVALID_SHORT
kINVALID_USHORT = cvar.kINVALID_USHORT
kINVALID_FLOAT = cvar.kINVALID_FLOAT
kINVALID_DOUBLE = cvar.kINVALID_DOUBLE
kStringPrefix = cvar.kStringPrefix

def logger_get(name):
    return _larcv.logger_get(name)
logger_get = _larcv.logger_get

def logger_get_shared():
    return _larcv.logger_get_shared()
logger_get_shared = _larcv.logger_get_shared

def logger_default_level(*args):
    return _larcv.logger_default_level(*args)
logger_default_level = _larcv.logger_default_level

def logger_force_level(l):
    return _larcv.logger_force_level(l)
logger_force_level = _larcv.logger_force_level

class larcv_base(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, larcv_base, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, larcv_base, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _larcv.new_larcv_base(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _larcv.delete_larcv_base
    __del__ = lambda self: None

    def logger(self):
        return _larcv.larcv_base_logger(self)

    def set_verbosity(self, level):
        return _larcv.larcv_base_set_verbosity(self, level)

    def name(self):
        return _larcv.larcv_base_name(self)
larcv_base_swigregister = _larcv.larcv_base_swigregister
larcv_base_swigregister(larcv_base)


def ConfigFile2String(fname):
    return _larcv.ConfigFile2String(fname)
ConfigFile2String = _larcv.ConfigFile2String

def CreatePSetFromFile(*args):
    return _larcv.CreatePSetFromFile(*args)
CreatePSetFromFile = _larcv.CreatePSetFromFile
class PSet(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, PSet, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, PSet, name)
    __repr__ = _swig_repr
    __swig_destroy__ = _larcv.delete_PSet
    __del__ = lambda self: None

    def __init__(self, *args):
        this = _larcv.new_PSet(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def name(self):
        return _larcv.PSet_name(self)

    def __eq__(self, rhs):
        return _larcv.PSet___eq__(self, rhs)

    def __ne__(self, rhs):
        return _larcv.PSet___ne__(self, rhs)

    def rename(self, name):
        return _larcv.PSet_rename(self, name)

    def clear(self):
        return _larcv.PSet_clear(self)

    def add(self, data):
        return _larcv.PSet_add(self, data)

    def add_value(self, key, value):
        return _larcv.PSet_add_value(self, key, value)

    def add_pset(self, *args):
        return _larcv.PSet_add_pset(self, *args)

    def dump(self, indent_size=0):
        return _larcv.PSet_dump(self, indent_size)

    def data_string(self):
        return _larcv.PSet_data_string(self)

    def get_pset(self, key):
        return _larcv.PSet_get_pset(self, key)

    def size(self):
        return _larcv.PSet_size(self)

    def keys(self):
        return _larcv.PSet_keys(self)

    def value_keys(self):
        return _larcv.PSet_value_keys(self)

    def pset_keys(self):
        return _larcv.PSet_pset_keys(self)

    def contains_value(self, key):
        return _larcv.PSet_contains_value(self, key)

    def contains_pset(self, key):
        return _larcv.PSet_contains_pset(self, key)
PSet_swigregister = _larcv.PSet_swigregister
PSet_swigregister(PSet)

class Watch(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Watch, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Watch, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _larcv.new_Watch()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _larcv.delete_Watch
    __del__ = lambda self: None

    def Start(self):
        return _larcv.Watch_Start(self)

    def WallTime(self):
        return _larcv.Watch_WallTime(self)

    def CPUTime(self):
        return _larcv.Watch_CPUTime(self)
Watch_swigregister = _larcv.Watch_swigregister
Watch_swigregister(Watch)

class ConfigManager(larcv_base):
    __swig_setmethods__ = {}
    for _s in [larcv_base]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, ConfigManager, name, value)
    __swig_getmethods__ = {}
    for _s in [larcv_base]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, ConfigManager, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _larcv.new_ConfigManager()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _larcv.delete_ConfigManager
    __del__ = lambda self: None
    if _newclass:
        get = staticmethod(_larcv.ConfigManager_get)
    else:
        get = _larcv.ConfigManager_get

    def AddConfigFile(self, cfg_file):
        return _larcv.ConfigManager_AddConfigFile(self, cfg_file)

    def AddConfigString(self, cfg_str):
        return _larcv.ConfigManager_AddConfigString(self, cfg_str)

    def GetConfig(self, cfg):
        return _larcv.ConfigManager_GetConfig(self, cfg)
ConfigManager_swigregister = _larcv.ConfigManager_swigregister
ConfigManager_swigregister(ConfigManager)

def ConfigManager_get():
    return _larcv.ConfigManager_get()
ConfigManager_get = _larcv.ConfigManager_get

class Extents_t(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Extents_t, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Extents_t, name)
    __repr__ = _swig_repr
    __swig_setmethods__["first"] = _larcv.Extents_t_first_set
    __swig_getmethods__["first"] = _larcv.Extents_t_first_get
    if _newclass:
        first = _swig_property(_larcv.Extents_t_first_get, _larcv.Extents_t_first_set)
    __swig_setmethods__["last"] = _larcv.Extents_t_last_set
    __swig_getmethods__["last"] = _larcv.Extents_t_last_get
    if _newclass:
        last = _swig_property(_larcv.Extents_t_last_get, _larcv.Extents_t_last_set)

    def __init__(self):
        this = _larcv.new_Extents_t()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _larcv.delete_Extents_t
    __del__ = lambda self: None
Extents_t_swigregister = _larcv.Extents_t_swigregister
Extents_t_swigregister(Extents_t)
kINVALID_INDEX = cvar.kINVALID_INDEX
kINVALID_INSTANCEID = cvar.kINVALID_INSTANCEID
kINVALID_PROJECTIONID = cvar.kINVALID_PROJECTIONID

kDISCONNECTED = _larcv.kDISCONNECTED
kDEAD = _larcv.kDEAD
kLOWNOISE = _larcv.kLOWNOISE
kNOISY = _larcv.kNOISY
kGOOD = _larcv.kGOOD
kUNKNOWN = _larcv.kUNKNOWN
kUnitUnknown = _larcv.kUnitUnknown
kUnitCM = _larcv.kUnitCM
kUnitWireTime = _larcv.kUnitWireTime
kPoolSum = _larcv.kPoolSum
kPoolAverage = _larcv.kPoolAverage
kPoolMax = _larcv.kPoolMax
kShapeShower = _larcv.kShapeShower
kShapeTrack = _larcv.kShapeTrack
kShapeUnknown = _larcv.kShapeUnknown
kPoint3D = _larcv.kPoint3D
kPointXY = _larcv.kPointXY
kPointYZ = _larcv.kPointYZ
kPointZX = _larcv.kPointZX
class Point2D(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Point2D, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Point2D, name)
    __repr__ = _swig_repr
    __swig_destroy__ = _larcv.delete_Point2D
    __del__ = lambda self: None

    def __init__(self, *args):
        this = _larcv.new_Point2D(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_setmethods__["x"] = _larcv.Point2D_x_set
    __swig_getmethods__["x"] = _larcv.Point2D_x_get
    if _newclass:
        x = _swig_property(_larcv.Point2D_x_get, _larcv.Point2D_x_set)
    __swig_setmethods__["y"] = _larcv.Point2D_y_set
    __swig_getmethods__["y"] = _larcv.Point2D_y_get
    if _newclass:
        y = _swig_property(_larcv.Point2D_y_get, _larcv.Point2D_y_set)

    def __eq__(self, rhs):
        return _larcv.Point2D___eq__(self, rhs)

    def __ne__(self, rhs):
        return _larcv.Point2D___ne__(self, rhs)

    def __imul__(self, rhs):
        return _larcv.Point2D___imul__(self, rhs)

    def __itruediv__(self, *args):
        return _larcv.Point2D___itruediv__(self, *args)
    __idiv__ = __itruediv__



    def __iadd__(self, rhs):
        return _larcv.Point2D___iadd__(self, rhs)

    def __isub__(self, rhs):
        return _larcv.Point2D___isub__(self, rhs)

    def __mul__(self, rhs):
        return _larcv.Point2D___mul__(self, rhs)

    def __truediv__(self, *args):
        return _larcv.Point2D___truediv__(self, *args)
    __div__ = __truediv__



    def __add__(self, rhs):
        return _larcv.Point2D___add__(self, rhs)

    def __sub__(self, rhs):
        return _larcv.Point2D___sub__(self, rhs)

    def squared_distance(self, pt):
        return _larcv.Point2D_squared_distance(self, pt)

    def distance(self, pt):
        return _larcv.Point2D_distance(self, pt)

    def direction(self, pt):
        return _larcv.Point2D_direction(self, pt)
Point2D_swigregister = _larcv.Point2D_swigregister
Point2D_swigregister(Point2D)
kINVALID_VOXELID = cvar.kINVALID_VOXELID
kNOTPRESENT = cvar.kNOTPRESENT
kNEGATIVEPEDESTAL = cvar.kNEGATIVEPEDESTAL
kINVALID_PRODUCER = cvar.kINVALID_PRODUCER

class Point3D(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Point3D, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Point3D, name)
    __repr__ = _swig_repr
    __swig_destroy__ = _larcv.delete_Point3D
    __del__ = lambda self: None

    def __init__(self, *args):
        this = _larcv.new_Point3D(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_setmethods__["x"] = _larcv.Point3D_x_set
    __swig_getmethods__["x"] = _larcv.Point3D_x_get
    if _newclass:
        x = _swig_property(_larcv.Point3D_x_get, _larcv.Point3D_x_set)
    __swig_setmethods__["y"] = _larcv.Point3D_y_set
    __swig_getmethods__["y"] = _larcv.Point3D_y_get
    if _newclass:
        y = _swig_property(_larcv.Point3D_y_get, _larcv.Point3D_y_set)
    __swig_setmethods__["z"] = _larcv.Point3D_z_set
    __swig_getmethods__["z"] = _larcv.Point3D_z_get
    if _newclass:
        z = _swig_property(_larcv.Point3D_z_get, _larcv.Point3D_z_set)

    def __eq__(self, rhs):
        return _larcv.Point3D___eq__(self, rhs)

    def __ne__(self, rhs):
        return _larcv.Point3D___ne__(self, rhs)

    def __itruediv__(self, *args):
        return _larcv.Point3D___itruediv__(self, *args)
    __idiv__ = __itruediv__



    def __imul__(self, rhs):
        return _larcv.Point3D___imul__(self, rhs)

    def __iadd__(self, rhs):
        return _larcv.Point3D___iadd__(self, rhs)

    def __isub__(self, rhs):
        return _larcv.Point3D___isub__(self, rhs)

    def __truediv__(self, *args):
        return _larcv.Point3D___truediv__(self, *args)
    __div__ = __truediv__



    def __mul__(self, rhs):
        return _larcv.Point3D___mul__(self, rhs)

    def __add__(self, rhs):
        return _larcv.Point3D___add__(self, rhs)

    def __sub__(self, rhs):
        return _larcv.Point3D___sub__(self, rhs)

    def squared_distance(self, pt):
        return _larcv.Point3D_squared_distance(self, pt)

    def distance(self, pt):
        return _larcv.Point3D_distance(self, pt)

    def direction(self, pt):
        return _larcv.Point3D_direction(self, pt)
Point3D_swigregister = _larcv.Point3D_swigregister
Point3D_swigregister(Point3D)

class Vertex(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Vertex, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Vertex, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _larcv.new_Vertex(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def reset(self, *args):
        return _larcv.Vertex_reset(self, *args)

    def as_point2d(self, point_type):
        return _larcv.Vertex_as_point2d(self, point_type)

    def as_point3d(self):
        return _larcv.Vertex_as_point3d(self)

    def as_point(self, point_type, x, y, z):
        return _larcv.Vertex_as_point(self, point_type, x, y, z)

    def x(self):
        return _larcv.Vertex_x(self)

    def y(self):
        return _larcv.Vertex_y(self)

    def z(self):
        return _larcv.Vertex_z(self)

    def t(self):
        return _larcv.Vertex_t(self)

    def __eq__(self, rhs):
        return _larcv.Vertex___eq__(self, rhs)

    def __ne__(self, rhs):
        return _larcv.Vertex___ne__(self, rhs)

    def __lt__(self, rhs):
        return _larcv.Vertex___lt__(self, rhs)

    def dump(self):
        return _larcv.Vertex_dump(self)
    __swig_destroy__ = _larcv.delete_Vertex
    __del__ = lambda self: None
Vertex_swigregister = _larcv.Vertex_swigregister
Vertex_swigregister(Vertex)

PARTICLE_PROCESS_STRLEN = _larcv.PARTICLE_PROCESS_STRLEN
class Particle(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Particle, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Particle, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _larcv.new_Particle(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _larcv.delete_Particle
    __del__ = lambda self: None

    def px(self):
        return _larcv.Particle_px(self)

    def py(self):
        return _larcv.Particle_py(self)

    def pz(self):
        return _larcv.Particle_pz(self)

    def p(self):
        return _larcv.Particle_p(self)

    def x(self):
        return _larcv.Particle_x(self)

    def y(self):
        return _larcv.Particle_y(self)

    def z(self):
        return _larcv.Particle_z(self)

    def t(self):
        return _larcv.Particle_t(self)

    def parent_x(self):
        return _larcv.Particle_parent_x(self)

    def parent_y(self):
        return _larcv.Particle_parent_y(self)

    def parent_z(self):
        return _larcv.Particle_parent_z(self)

    def parent_t(self):
        return _larcv.Particle_parent_t(self)

    def ancestor_x(self):
        return _larcv.Particle_ancestor_x(self)

    def ancestor_y(self):
        return _larcv.Particle_ancestor_y(self)

    def ancestor_z(self):
        return _larcv.Particle_ancestor_z(self)

    def ancestor_t(self):
        return _larcv.Particle_ancestor_t(self)

    def id(self, *args):
        return _larcv.Particle_id(self, *args)

    def mcst_index(self, *args):
        return _larcv.Particle_mcst_index(self, *args)

    def mct_index(self, *args):
        return _larcv.Particle_mct_index(self, *args)

    def shape(self, *args):
        return _larcv.Particle_shape(self, *args)

    def nu_current_type(self, *args):
        return _larcv.Particle_nu_current_type(self, *args)

    def nu_interaction_type(self, *args):
        return _larcv.Particle_nu_interaction_type(self, *args)

    def track_id(self, *args):
        return _larcv.Particle_track_id(self, *args)

    def pdg_code(self, *args):
        return _larcv.Particle_pdg_code(self, *args)

    def momentum(self, px, py, pz):
        return _larcv.Particle_momentum(self, px, py, pz)

    def position(self, *args):
        return _larcv.Particle_position(self, *args)

    def end_position(self, *args):
        return _larcv.Particle_end_position(self, *args)

    def first_step(self, *args):
        return _larcv.Particle_first_step(self, *args)

    def last_step(self, *args):
        return _larcv.Particle_last_step(self, *args)

    def distance_travel(self, *args):
        return _larcv.Particle_distance_travel(self, *args)

    def energy_init(self, *args):
        return _larcv.Particle_energy_init(self, *args)

    def energy_deposit(self, *args):
        return _larcv.Particle_energy_deposit(self, *args)

    def creation_process(self, *args):
        return _larcv.Particle_creation_process(self, *args)

    def parent_track_id(self, *args):
        return _larcv.Particle_parent_track_id(self, *args)

    def parent_pdg_code(self, *args):
        return _larcv.Particle_parent_pdg_code(self, *args)

    def parent_position(self, *args):
        return _larcv.Particle_parent_position(self, *args)

    def ancestor_track_id(self, *args):
        return _larcv.Particle_ancestor_track_id(self, *args)

    def ancestor_pdg_code(self, *args):
        return _larcv.Particle_ancestor_pdg_code(self, *args)

    def ancestor_position(self, *args):
        return _larcv.Particle_ancestor_position(self, *args)

    def dump(self):
        return _larcv.Particle_dump(self)
Particle_swigregister = _larcv.Particle_swigregister
Particle_swigregister(Particle)

class Voxel(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Voxel, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Voxel, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _larcv.new_Voxel(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _larcv.delete_Voxel
    __del__ = lambda self: None

    def id(self):
        return _larcv.Voxel_id(self)

    def value(self):
        return _larcv.Voxel_value(self)

    def set(self, id, value):
        return _larcv.Voxel_set(self, id, value)

    def __iadd__(self, value):
        return _larcv.Voxel___iadd__(self, value)

    def __isub__(self, value):
        return _larcv.Voxel___isub__(self, value)

    def __imul__(self, factor):
        return _larcv.Voxel___imul__(self, factor)

    def __itruediv__(self, *args):
        return _larcv.Voxel___itruediv__(self, *args)
    __idiv__ = __itruediv__



    def __eq__(self, *args):
        return _larcv.Voxel___eq__(self, *args)

    def __lt__(self, *args):
        return _larcv.Voxel___lt__(self, *args)

    def __le__(self, *args):
        return _larcv.Voxel___le__(self, *args)

    def __gt__(self, *args):
        return _larcv.Voxel___gt__(self, *args)

    def __ge__(self, *args):
        return _larcv.Voxel___ge__(self, *args)
Voxel_swigregister = _larcv.Voxel_swigregister
Voxel_swigregister(Voxel)

class kINVALID_VOXEL(Voxel):
    __swig_setmethods__ = {}
    for _s in [Voxel]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, kINVALID_VOXEL, name, value)
    __swig_getmethods__ = {}
    for _s in [Voxel]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, kINVALID_VOXEL, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    if _newclass:
        getInstance = staticmethod(_larcv.kINVALID_VOXEL_getInstance)
    else:
        getInstance = _larcv.kINVALID_VOXEL_getInstance
    __swig_destroy__ = _larcv.delete_kINVALID_VOXEL
    __del__ = lambda self: None
kINVALID_VOXEL_swigregister = _larcv.kINVALID_VOXEL_swigregister
kINVALID_VOXEL_swigregister(kINVALID_VOXEL)

def kINVALID_VOXEL_getInstance():
    return _larcv.kINVALID_VOXEL_getInstance()
kINVALID_VOXEL_getInstance = _larcv.kINVALID_VOXEL_getInstance

class VoxelSet(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VoxelSet, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VoxelSet, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _larcv.new_VoxelSet()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _larcv.delete_VoxelSet
    __del__ = lambda self: None

    def as_vector(self):
        return _larcv.VoxelSet_as_vector(self)

    def find(self, id):
        return _larcv.VoxelSet_find(self, id)

    def sum(self):
        return _larcv.VoxelSet_sum(self)

    def mean(self):
        return _larcv.VoxelSet_mean(self)

    def max(self):
        return _larcv.VoxelSet_max(self)

    def min(self):
        return _larcv.VoxelSet_min(self)

    def size(self):
        return _larcv.VoxelSet_size(self)

    def clear_data(self):
        return _larcv.VoxelSet_clear_data(self)

    def reserve(self, num):
        return _larcv.VoxelSet_reserve(self, num)

    def threshold(self, min, max):
        return _larcv.VoxelSet_threshold(self, min, max)

    def threshold_min(self, min):
        return _larcv.VoxelSet_threshold_min(self, min)

    def threshold_max(self, max):
        return _larcv.VoxelSet_threshold_max(self, max)

    def add(self, vox):
        return _larcv.VoxelSet_add(self, vox)

    def insert(self, vox):
        return _larcv.VoxelSet_insert(self, vox)

    def emplace(self, *args):
        return _larcv.VoxelSet_emplace(self, *args)

    def id(self, *args):
        return _larcv.VoxelSet_id(self, *args)

    def __iadd__(self, value):
        return _larcv.VoxelSet___iadd__(self, value)

    def __isub__(self, value):
        return _larcv.VoxelSet___isub__(self, value)

    def __imul__(self, factor):
        return _larcv.VoxelSet___imul__(self, factor)

    def __itruediv__(self, *args):
        return _larcv.VoxelSet___itruediv__(self, *args)
    __idiv__ = __itruediv__


VoxelSet_swigregister = _larcv.VoxelSet_swigregister
VoxelSet_swigregister(VoxelSet)

class VoxelSetArray(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VoxelSetArray, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VoxelSetArray, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _larcv.new_VoxelSetArray()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _larcv.delete_VoxelSetArray
    __del__ = lambda self: None

    def size(self):
        return _larcv.VoxelSetArray_size(self)

    def voxel_set(self, id):
        return _larcv.VoxelSetArray_voxel_set(self, id)

    def as_vector(self):
        return _larcv.VoxelSetArray_as_vector(self)

    def sum(self):
        return _larcv.VoxelSetArray_sum(self)

    def mean(self):
        return _larcv.VoxelSetArray_mean(self)

    def max(self):
        return _larcv.VoxelSetArray_max(self)

    def min(self):
        return _larcv.VoxelSetArray_min(self)

    def threshold(self, min, max):
        return _larcv.VoxelSetArray_threshold(self, min, max)

    def threshold_min(self, min):
        return _larcv.VoxelSetArray_threshold_min(self, min)

    def threshold_max(self, max):
        return _larcv.VoxelSetArray_threshold_max(self, max)

    def clear_data(self):
        return _larcv.VoxelSetArray_clear_data(self)

    def resize(self, num):
        return _larcv.VoxelSetArray_resize(self, num)

    def writeable_voxel_set(self, id):
        return _larcv.VoxelSetArray_writeable_voxel_set(self, id)

    def emplace(self, *args):
        return _larcv.VoxelSetArray_emplace(self, *args)

    def insert(self, voxel_v):
        return _larcv.VoxelSetArray_insert(self, voxel_v)

    def move(self, orig):
        return _larcv.VoxelSetArray_move(self, orig)
VoxelSetArray_swigregister = _larcv.VoxelSetArray_swigregister
VoxelSetArray_swigregister(VoxelSetArray)

class EventBase(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, EventBase, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, EventBase, name)
    __repr__ = _swig_repr

    def clear(self):
        return _larcv.EventBase_clear(self)

    def initialize(self, arg2):
        return _larcv.EventBase_initialize(self, arg2)

    def serialize(self, group):
        return _larcv.EventBase_serialize(self, group)

    def deserialize(self, group, entry):
        return _larcv.EventBase_deserialize(self, group, entry)

    def __init__(self):
        this = _larcv.new_EventBase()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _larcv.delete_EventBase
    __del__ = lambda self: None
EventBase_swigregister = _larcv.EventBase_swigregister
EventBase_swigregister(EventBase)

class DataProductFactoryBase(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DataProductFactoryBase, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DataProductFactoryBase, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _larcv.delete_DataProductFactoryBase
    __del__ = lambda self: None

    def create(self):
        return _larcv.DataProductFactoryBase_create(self)
DataProductFactoryBase_swigregister = _larcv.DataProductFactoryBase_swigregister
DataProductFactoryBase_swigregister(DataProductFactoryBase)

class DataProductFactory(larcv_base):
    __swig_setmethods__ = {}
    for _s in [larcv_base]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, DataProductFactory, name, value)
    __swig_getmethods__ = {}
    for _s in [larcv_base]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, DataProductFactory, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _larcv.new_DataProductFactory()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _larcv.delete_DataProductFactory
    __del__ = lambda self: None
    if _newclass:
        get = staticmethod(_larcv.DataProductFactory_get)
    else:
        get = _larcv.DataProductFactory_get

    def add_factory(self, type, factory):
        return _larcv.DataProductFactory_add_factory(self, type, factory)

    def create(self, *args):
        return _larcv.DataProductFactory_create(self, *args)

    def list(self):
        return _larcv.DataProductFactory_list(self)

    def unique_product_count(self):
        return _larcv.DataProductFactory_unique_product_count(self)

    def product_names(self):
        return _larcv.DataProductFactory_product_names(self)
DataProductFactory_swigregister = _larcv.DataProductFactory_swigregister
DataProductFactory_swigregister(DataProductFactory)

def DataProductFactory_get():
    return _larcv.DataProductFactory_get()
DataProductFactory_get = _larcv.DataProductFactory_get

class IOManager(larcv_base):
    __swig_setmethods__ = {}
    for _s in [larcv_base]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, IOManager, name, value)
    __swig_getmethods__ = {}
    for _s in [larcv_base]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, IOManager, name)
    __repr__ = _swig_repr
    kREAD = _larcv.IOManager_kREAD
    kWRITE = _larcv.IOManager_kWRITE
    kBOTH = _larcv.IOManager_kBOTH

    def __init__(self, *args):
        this = _larcv.new_IOManager(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _larcv.delete_IOManager
    __del__ = lambda self: None

    def io_mode(self):
        return _larcv.IOManager_io_mode(self)

    def reset(self):
        return _larcv.IOManager_reset(self)

    def add_in_file(self, *args):
        return _larcv.IOManager_add_in_file(self, *args)

    def clear_in_file(self):
        return _larcv.IOManager_clear_in_file(self)

    def set_out_file(self, name):
        return _larcv.IOManager_set_out_file(self, name)

    def producer_id(self, name):
        return _larcv.IOManager_producer_id(self, name)

    def configure(self, cfg):
        return _larcv.IOManager_configure(self, cfg)

    def initialize(self):
        return _larcv.IOManager_initialize(self)

    def read_entry(self, index, force_reload=False):
        return _larcv.IOManager_read_entry(self, index, force_reload)

    def save_entry(self):
        return _larcv.IOManager_save_entry(self)

    def finalize(self):
        return _larcv.IOManager_finalize(self)

    def clear_entry(self):
        return _larcv.IOManager_clear_entry(self)

    def set_id(self, run, subrun, event):
        return _larcv.IOManager_set_id(self, run, subrun, event)

    def current_entry(self):
        return _larcv.IOManager_current_entry(self)

    def get_n_entries_out(self):
        return _larcv.IOManager_get_n_entries_out(self)

    def get_file_out_name(self):
        return _larcv.IOManager_get_file_out_name(self)

    def get_n_entries(self):
        return _larcv.IOManager_get_n_entries(self)

    def get_data(self, *args):
        return _larcv.IOManager_get_data(self, *args)

    def event_id(self):
        return _larcv.IOManager_event_id(self)

    def last_event_id(self):
        return _larcv.IOManager_last_event_id(self)

    def producer_list(self, type):
        return _larcv.IOManager_producer_list(self, type)

    def product_list(self):
        return _larcv.IOManager_product_list(self)

    def file_list(self):
        return _larcv.IOManager_file_list(self)
IOManager_swigregister = _larcv.IOManager_swigregister
IOManager_swigregister(IOManager)

class EventParticle(EventBase):
    __swig_setmethods__ = {}
    for _s in [EventBase]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, EventParticle, name, value)
    __swig_getmethods__ = {}
    for _s in [EventBase]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, EventParticle, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _larcv.new_EventParticle()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _larcv.delete_EventParticle
    __del__ = lambda self: None

    def clear(self):
        return _larcv.EventParticle_clear(self)

    def set(self, part_v):
        return _larcv.EventParticle_set(self, part_v)

    def append(self, part):
        return _larcv.EventParticle_append(self, part)

    def emplace_back(self, part):
        return _larcv.EventParticle_emplace_back(self, part)

    def emplace(self, part_v):
        return _larcv.EventParticle_emplace(self, part_v)

    def as_vector(self):
        return _larcv.EventParticle_as_vector(self)

    def size(self):
        return _larcv.EventParticle_size(self)

    def initialize(self, group):
        return _larcv.EventParticle_initialize(self, group)

    def serialize(self, group):
        return _larcv.EventParticle_serialize(self, group)

    def deserialize(self, group, entry):
        return _larcv.EventParticle_deserialize(self, group, entry)
    if _newclass:
        to_particle = staticmethod(_larcv.EventParticle_to_particle)
    else:
        to_particle = _larcv.EventParticle_to_particle
EventParticle_swigregister = _larcv.EventParticle_swigregister
EventParticle_swigregister(EventParticle)

def EventParticle_to_particle(e):
    return _larcv.EventParticle_to_particle(e)
EventParticle_to_particle = _larcv.EventParticle_to_particle

class EventParticleFactory(DataProductFactoryBase):
    __swig_setmethods__ = {}
    for _s in [DataProductFactoryBase]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, EventParticleFactory, name, value)
    __swig_getmethods__ = {}
    for _s in [DataProductFactoryBase]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, EventParticleFactory, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _larcv.new_EventParticleFactory()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _larcv.delete_EventParticleFactory
    __del__ = lambda self: None

    def create(self):
        return _larcv.EventParticleFactory_create(self)
EventParticleFactory_swigregister = _larcv.EventParticleFactory_swigregister
EventParticleFactory_swigregister(EventParticleFactory)

# This file is compatible with both classic and new-style classes.


